<?php

/**
 * PluginrtShopOrderToStockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopOrderToStockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopOrderToStockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopOrderToStock');
    }

  /**
   * Return a query object, creating a new one if needed.
   *
   * @param Doctrine_Query $query
   * @return Doctrine_Query
   */
  public function getQuery(Doctrine_Query $query = null)
  {
    if(is_null($query))
    {
      $query = parent::createQuery('ots');
    }
    return $query;
  }
}