<?php

/**
 * PluginrtShopPromotionProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopPromotionProductTable extends rtShopPromotionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopPromotionProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopPromotionProduct');
    }
}