<?php

/**
 * PluginrtShopOrderToStockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopOrderToStockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopOrderToStockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopOrderToStock');
    }
}