<?php

/**
 * PluginrtShopProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginrtShopProduct extends BasertShopProduct
{
  private $_rt_shop_stock_array = null,
          $_price_arrays = array();
  
  public function getTypeNice()
  {
    return 'Product';
  }

  public function getStockSkus()
  {
    $string = '';
    foreach($this->rtShopStocks as $stock)
    {
      $string .= ' '.$stock->sku;
    }
    return $string;
  }

  /**
   * Return an array of stock and associated variation for a given product.
   *
   * @param Doctrine_Query $query
   * @return array
   */
  public function getStocksAsArray($query = null)
  {
    if(is_null($this->_rt_shop_stock_array))
    {
      $this->_rt_shop_stock_array = Doctrine::getTable('rtShopStock')->getForProductAsArray($this->getId(), $query);
    }
    return $this->_rt_shop_stock_array;
  }
}