<?php

/**
 * PluginrtShopStockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopStockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopStockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopStock');
    }
}