<?php

/**
 * PluginrtShopStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginrtShopStock extends BasertShopStock
{
  public function getTidyVariationsList()
  {
    exit;
    return $this->rtShopVariations;
  }

  /**
   * Adjust stock quantity
   *
   * @param Integer $quantity Ordered stock quanity
   * @return Object
   */
  public function adjustQuantityBy($quantity)
  {
    if($quantity > 0)
    {
      $adjusted_quantity = $this['quantity'] - $quantity;
      $this->_set('quantity', $adjusted_quantity);
    }

    return $this;
  }
}