<?php

/**
 * PluginrtShopVariationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopVariationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopVariationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopVariation');
    }
}