<?php

/**
 * PluginrtShopProductToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopProductToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopProductToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopProductToCategory');
    }
}