<?php

/**
 * PluginrtShopStockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopStockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopStockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopStock');
    }

  /**
   * Returns a Doctrine_Query object.
   *
   * @param Doctrine_Query $query
   * @return Doctrine_Query
   */
  private function getQuery(Doctrine_Query $query = null)
  {
    if (is_null($query))
    {
      $query = $this->getQueryObject()->from($this->getComponentName() .' s');
    }
    return $query;
  }
}