<?php

/**
 * PluginrtShopProductToPromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopProductToPromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopProductToPromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopProductToPromotion');
    }
}