<?php

/**
 * PluginrtShopCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopCategoryTable extends rtPageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopCategory');
    }
}