<?php

/**
 * PluginrtShopPromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopPromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopPromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopPromotion');
    }
}