<?php

/**
 * PluginrtShopProductToAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopProductToAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopProductToAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopProductToAttribute');
    }
}