<?php

/**
 * PluginrtShopAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopAttribute');
    }
}