<?php

/**
 * PluginrtShopPromotionProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginrtShopPromotionProduct extends BasertShopPromotionProduct
{
  /**
   * Constructor
   *
   * @return void
   */
  public function construct ()
  {
    if($this->isNew()) {
      $this->setType('rtShopPromotionProduct');
    }
  }

  /**
   * Return availability status of promotion
   *
   * @return boolean true if promotion is available
   */
  public function isAvailable()
  {
    $date_now  = date("Y-m-d H:i:s");
    $date_from = $this->getDateFrom();
    $date_to   = $this->getDateTo();

    return (($date_from <= $date_now || is_null($date_from)) && ($date_to >= $date_now || is_null($date_to))) ? true : false;
  }
}