<?php

/**
 * PluginrtShopVoucherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopVoucherTable extends rtShopPromotionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopVoucherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopVoucher');
    }
}