<?php

/**
 * PluginrtShopProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopProductTable extends rtPageTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginrtShopProductTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginrtShopProduct');
  }
  
}