<?php

/**
 * PluginrtShopPromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginrtShopPromotion extends BasertShopPromotion
{
  const REDUCTION_TYPE_PERCENTAGE   = 'percentageOff';
  const REDUCTION_TYPE_DOLLAR       = 'dollarOff';

  public function getTypeNice()
  {
    return 'Promotion';
  }

  public function isPercentageOff()
  {
    return $this->getReductionType() == self::REDUCTION_TYPE_PERCENTAGE;
  }

  public function isDollarOff()
  {
    return !$this->isPercentageOff();
  }

  public function isValueOff()
  {
    return $this->isDollarOff();
  }

  /**
   * Proxy save function. Check for title not null or empty
   *
   * @param   Doctrine_Connection $conn
   * @return  void
   * @throws  SteerShopException
   */
  public function save(Doctrine_Connection $conn = null)
  {
    // Only promotions with a title can be saved.
    if ($this['title'] == null || empty($this['title'])) {
      throw new Exception('Cannot save rtShopPromotion with an empty or null title.');
    }

    parent::save();
  }
}