<?php

/**
 * PluginrtShopProductToRelatedCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopProductToRelatedCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopProductToRelatedCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopProductToRelatedCategory');
    }
}