<?php

/**
 * PluginrtShopStockToVariationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopStockToVariationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopStockToVariationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopStockToVariation');
    }
}