<?php

/**
 * PluginrtShopPromotionCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopPromotionCartTable extends rtShopPromotionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopPromotionCartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopPromotionCart');
    }
}