<?php

/**
 * PluginrtShopOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginrtShopOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginrtShopOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginrtShopOrder');
    }
}