<?php if(sfConfig::get('app_rt_shop_is_private', false)): ?>

_shop_product:
  enabled:     true

<?php else: ?>

show:
  enabled:     true

_shopProductFeatured:
  enabled:  true
  lifetime: 1800

<?php endif; ?>
