<?php if(sfConfig::get('app_rt_shop_is_private', false)): ?>

_shop_category:
  enabled:     true

<?php else: ?>

index:
  enabled:     true
show:
  enabled:     true
_navigation:
  enabled:     true
  contextual:  true

<?php endif; ?>
