rtShopProduct:
  actAs:
    rtSearchTemplate:
      fields:      [title, content, description, sku, stock_skus, tags_as_string]
  columns:
    sku:                      { type: string(255) }
    is_featured:              { type: boolean, default: false }
    backorder_allowed:        { type: boolean, default: false }
    is_taxable:               { type: boolean, default: true }
  inheritance:
    type:              concrete
    extends:           rtPage
  relations:
    rtShopCategories:
      class: rtShopCategory
      local: product_id
      foreign:  category_id
      refClass: rtShopProductToCategory
    rtShopStocks:
      local: id
      foreign: product_id
    rtShopAttributes:
      class: rtShopAttribute
      local: product_id
      foreign:  attribute_id
      refClass: rtShopProductToAttribute
    rtShopPromotions:
      class: rtShopPromotion
      local: product_id
      foreign:  promotion_id
      refClass: rtShopProductToPromotion
    rtShopProducts:
      class: rtShopProduct
      local: product_id
      foreign:  product_id_target
      refClass: rtShopProductToProduct
    rtShopProductsLinked:
      class: rtShopProduct
      local: product_id_target
      foreign:  product_id
      refClass: rtShopProductToProduct

rtShopProductToPromotion:
  columns:
    product_id:
      type: integer
      primary: true
    promotion_id:
      type: integer
      primary: true
  relations:
  relations:
    rtShopProduct:
      local: product_id
      foreign: id
      onDelete: CASCADE
    rtShopPromotionProduct:
      local: promotion_id
      foreign: id
      onDelete: CASCADE

rtShopProductToProduct:
  columns:
    position: integer(3)
    product_id:
      type: integer
      primary: true
    product_id_target:
      type: integer
      primary: true
    position: integer
  relations:
    rtShopProduct:
      local: product_id
      foreignAlias: rtShopProducts
      foreign: id
      onDelete: CASCADE
    rtShopProductTarget:
      class: rtShopProduct
      local: product_id_target
      foreignAlias: rtShopProductsLinked
      foreign: id
      onDelete: CASCADE
  checks:
    self_reference_check: product_id != product_id_target

rtShopStock:
  columns:
    product_id:               { type: integer }
    promotion_id:             { type: integer }
    quantity:                 { type: integer, default: 0 }
    sku:                      { type: string(255) }
    price_retail:             { type: float, default: 0.00 }
    price_promotion:          { type: float, default: 0.00 }
    price_wholesale:          { type: float, default: 0.00 }
    length:                   { type: float, default: 0.00 }
    width:                    { type: float, default: 0.00 }
    height:                   { type: float, default: 0.00 }
    weight:                   { type: float, default: 0.00 }
  relations:
    rtShopProduct:
      local: product_id
      foreign: id
      foreignAlias: rtShopStocks
      onDelete: CASCADE
    rtShopPromotionProduct:
      local: promotion_id
      foreign: id
      foreignAlias: rtShopStocks
    rtShopVariations:
      class: rtShopVariation
      local: stock_id
      foreign: variation_id
      foreignAlias: rtShopStocks
      refClass: rtShopStockToVariation
#    rtShopOrders:
#      class: rtShopOrder
#      local: stock_id
#      foreign:  order_id
#      refClass: rtShopOrderToStock



rtShopStockToVariation:
  columns:
    stock_id:
      type: integer
      primary: true
    variation_id:
      type: integer
      primary: true
  relations:
    rtShopStock:
      local: stock_id
      foreign: id
      onDelete: CASCADE
    rtShopVariation:
      local: variation_id
      foreign: id
      onDelete: CASCADE



rtShopProductToAttribute:
  columns:
    position: integer(3)
    product_id:
      type: integer
      primary: true
    attribute_id:
      type: integer
      primary: true
    position: integer
  relations:
    rtShopProduct:
      local: product_id
      foreignAlias: rtShopAttributes
      foreign: id
      onDelete: CASCADE
    rtShopAttribute:
      local: attribute_id
      foreignAlias: rtShopProducts
      foreign: id
      onDelete: CASCADE



rtShopVariation:
  columns:
    title:                   { type: string(255) }
    position:                { type: integer }
    image:                   { type: string(255) }
    attribute_id:            { type: integer }
  relations:
    rtShopAttribute:
      local: attribute_id
      foreign: id
      foreignAlias: rtShopVariations
      onDelete: CASCADE



rtShopAttribute:
  columns:
    title:                   { type: string(100) }
    display_title:           { type: string(100) }
    description:             { type: string(255) }
  relations:
    rtShopProducts:
      class: rtShopProduct
      local: attribute_id
      foreign:  product_id
      refClass: rtShopProductToAttribute


rtShopProductToCategory:
  columns:
    category_id:
      type: integer
      primary: true
    product_id:
      type: integer
      primary: true
  relations:
    rtShopCategory:  { onDelete: CASCADE, local: category_id, foreign: id }
    rtShopProduct:  { onDelete: CASCADE, local: product_id, foreign: id }



rtShopCategory:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    menu_title:               string(255)
    display_in_menu:          { type: boolean, default: 1 }
  inheritance:
    type:              concrete
    extends:           rtPage
  relations:
    rtShopProducts:
      class: rtShopProduct
      local: category_id
      foreign:  product_id
      refClass: rtShopProductToCategory




